void test();
void memvoid();
void * getHeader(void * p);
void * getFooter(void * p);
int getSize(void * headerPointer);
int getAllocation(void * p);
char * createExtremities(char * p, int size, int allocated);
void mydeallocate(void * ptr, char * b, int a, int id);
void setValue(void * p, int size, int allocation);
void * getNext(void * ptr);
void * getPrevious(void * ptr);
void initialize();
void * findFit(int extendedSize);
void * myallocate(size_t size, char * b, int a, int id);
void coalesce(void * ptr);
void initializeMemory();
void initializePage();
void swap_in(int16_t newPage, int des);
int16_t swap_out(int16_t page);
static void seg_handler(int sig, siginfo_t * si, void * unused);
void install_seg_handler();